language: cpp
script:
 - make dmd
 - ./sfn -v
 #- make gdc
 #- ./sfn -v
 - ronn -r sfn.1.ronn
before_install:
 - sudo apt-get update -qq
 - wget http://ftp.digitalmars.com/dmd_2.060-0_i386.deb
 - sudo apt-get install -qq gcc-multilib
 - sudo dpkg -i dmd_2.060-0_i386.deb
 - sudo apt-get -f install -qq
 #- sudo apt-get install -qq gdc
 - sudo apt-get install -qq ruby
 - gem install ronn
