language: cpp
script:
 - make man
 - make
 - ./sfn -v
 #- make gdc
 #- ./sfn -v
before_install:
 - sudo apt-get update -qq
 - wget http://ftp.digitalmars.com/dmd_2.062-0_i386.deb
 - sudo apt-get install -qq gcc gcc-multilib libc6 libgcc1 libstdc++6 xdg-utils libc6-dev
 - sudo dpkg -i dmd_2.062-0_i386.deb
 - sudo apt-get -f install -qq
 #- sudo apt-get install -qq gdc
 - sudo apt-get install -qq ruby
 - gem install ronn
