language: cpp
before_install:
 - sudo apt-get update -qq
 - curl -s http://dlang.org/download.html | grep download | grep deb | cut -d'"' -f4 | head -n 2 | xargs wget
 - sudo apt-get install -qq gcc gcc-multilib libc6 libgcc1 libstdc++6 xdg-utils libc6-dev
 - sudo dpkg -i dmd_*_amd64.deb || sudo dpkg -i dmd_*_i386.deb
 - sudo apt-get -f install -qq
 #- sudo apt-get install -qq gdc
 - sudo apt-get install -qq ruby
 - gem install ronn
script:
 - make man
 - make
 - ./sfn -v
 #- make gdc
 #- ./sfn -v
